// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { ListRepositoriesData, ListRepositoriesResponses, ListRepositoriesErrors, CreateRepositoryData, CreateRepositoryResponses, CreateRepositoryErrors, DeleteRepositoryData, DeleteRepositoryResponses, DeleteRepositoryErrors, GetRepositoryData, GetRepositoryResponses, GetRepositoryErrors, ListGroupMembersData, ListGroupMembersResponses, ReplaceGroupMembersData, ReplaceGroupMembersResponses, ReplaceGroupMembersErrors, ListGrantsData, ListGrantsResponses, ReplaceGrantsData, ReplaceGrantsResponses, ReplaceGrantsErrors, GetRetentionPolicyData, GetRetentionPolicyResponses, ReplaceRetentionPolicyData, ReplaceRetentionPolicyResponses, ReplaceRetentionPolicyErrors, ListGroupsData, ListGroupsResponses, CreateGroupData, CreateGroupResponses, CreateGroupErrors, DeleteGroupData, DeleteGroupResponses, GetGroupData, GetGroupResponses, ReplaceGroupData, ReplaceGroupResponses, ReplaceGroupErrors, ReadRawContentData, ReadRawContentResponses, ReadRawContentErrors, ReadOciManifestData, ReadOciManifestResponses, ReadOciManifestErrors, ReadOciBlobData, ReadOciBlobResponses, ReadOciBlobErrors, ReadMavenAssetData, ReadMavenAssetResponses, ReadMavenAssetErrors, CreatePublishSessionData, CreatePublishSessionResponses, CreatePublishSessionErrors, GetPublishSessionData, GetPublishSessionResponses, GetPublishSessionErrors, UploadPublishObjectData, UploadPublishObjectResponses, UploadPublishObjectErrors, CommitPublishSessionData, CommitPublishSessionResponses, CommitPublishSessionErrors, ListArtifactsData, ListArtifactsResponses, DeleteArtifactData, DeleteArtifactResponses, GetArtifactData, GetArtifactResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const listRepositories = <ThrowOnError extends boolean = false>(options?: Options<ListRepositoriesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListRepositoriesResponses, ListRepositoriesErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/repositories',
        ...options
    });
};

export const createRepository = <ThrowOnError extends boolean = false>(options: Options<CreateRepositoryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateRepositoryResponses, CreateRepositoryErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/repositories',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const deleteRepository = <ThrowOnError extends boolean = false>(options: Options<DeleteRepositoryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteRepositoryResponses, DeleteRepositoryErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/repositories/{repositoryId}',
        ...options
    });
};

export const getRepository = <ThrowOnError extends boolean = false>(options: Options<GetRepositoryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetRepositoryResponses, GetRepositoryErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/repositories/{repositoryId}',
        ...options
    });
};

export const listGroupMembers = <ThrowOnError extends boolean = false>(options: Options<ListGroupMembersData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ListGroupMembersResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/groups/{groupId}/members',
        ...options
    });
};

export const replaceGroupMembers = <ThrowOnError extends boolean = false>(options: Options<ReplaceGroupMembersData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<ReplaceGroupMembersResponses, ReplaceGroupMembersErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/groups/{groupId}/members',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const listGrants = <ThrowOnError extends boolean = false>(options: Options<ListGrantsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ListGrantsResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/repositories/{repositoryId}/grants',
        ...options
    });
};

export const replaceGrants = <ThrowOnError extends boolean = false>(options: Options<ReplaceGrantsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<ReplaceGrantsResponses, ReplaceGrantsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/repositories/{repositoryId}/grants',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getRetentionPolicy = <ThrowOnError extends boolean = false>(options: Options<GetRetentionPolicyData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetRetentionPolicyResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/repositories/{repositoryId}/retention-policy',
        ...options
    });
};

export const replaceRetentionPolicy = <ThrowOnError extends boolean = false>(options: Options<ReplaceRetentionPolicyData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<ReplaceRetentionPolicyResponses, ReplaceRetentionPolicyErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/repositories/{repositoryId}/retention-policy',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const listGroups = <ThrowOnError extends boolean = false>(options?: Options<ListGroupsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListGroupsResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/groups',
        ...options
    });
};

export const createGroup = <ThrowOnError extends boolean = false>(options: Options<CreateGroupData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateGroupResponses, CreateGroupErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/groups',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const deleteGroup = <ThrowOnError extends boolean = false>(options: Options<DeleteGroupData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteGroupResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/groups/{groupId}',
        ...options
    });
};

export const getGroup = <ThrowOnError extends boolean = false>(options: Options<GetGroupData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetGroupResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/groups/{groupId}',
        ...options
    });
};

export const replaceGroup = <ThrowOnError extends boolean = false>(options: Options<ReplaceGroupData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<ReplaceGroupResponses, ReplaceGroupErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/groups/{groupId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const readRawContent = <ThrowOnError extends boolean = false>(options: Options<ReadRawContentData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ReadRawContentResponses, ReadRawContentErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            },
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/raw/{repository}/content/{path}',
        ...options
    });
};

export const readOciManifest = <ThrowOnError extends boolean = false>(options: Options<ReadOciManifestData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ReadOciManifestResponses, ReadOciManifestErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v2/{name}/manifests/{reference}',
        ...options
    });
};

export const readOciBlob = <ThrowOnError extends boolean = false>(options: Options<ReadOciBlobData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ReadOciBlobResponses, ReadOciBlobErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v2/{name}/blobs/{digest}',
        ...options
    });
};

export const readMavenAsset = <ThrowOnError extends boolean = false>(options: Options<ReadMavenAssetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ReadMavenAssetResponses, ReadMavenAssetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            },
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/repository/maven/{repository}/{assetPath}',
        ...options
    });
};

export const createPublishSession = <ThrowOnError extends boolean = false>(options: Options<CreatePublishSessionData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreatePublishSessionResponses, CreatePublishSessionErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/repositories/{repositoryId}/publish-sessions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getPublishSession = <ThrowOnError extends boolean = false>(options: Options<GetPublishSessionData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetPublishSessionResponses, GetPublishSessionErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/publish-sessions/{sessionId}',
        ...options
    });
};

export const uploadPublishObject = <ThrowOnError extends boolean = false>(options: Options<UploadPublishObjectData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UploadPublishObjectResponses, UploadPublishObjectErrors, ThrowOnError>({
        bodySerializer: null,
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/publish-sessions/{sessionId}/objects/{objectName}',
        ...options,
        headers: {
            'Content-Type': 'application/octet-stream',
            ...options.headers
        }
    });
};

export const commitPublishSession = <ThrowOnError extends boolean = false>(options: Options<CommitPublishSessionData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CommitPublishSessionResponses, CommitPublishSessionErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/publish-sessions/{sessionId}:commit',
        ...options
    });
};

export const listArtifacts = <ThrowOnError extends boolean = false>(options: Options<ListArtifactsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ListArtifactsResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/repositories/{repositoryId}/artifacts',
        ...options
    });
};

export const deleteArtifact = <ThrowOnError extends boolean = false>(options: Options<DeleteArtifactData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteArtifactResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/repositories/{repositoryId}/artifacts/{artifactId}',
        ...options
    });
};

export const getArtifact = <ThrowOnError extends boolean = false>(options: Options<GetArtifactData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetArtifactResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/repositories/{repositoryId}/artifacts/{artifactId}',
        ...options
    });
};