// This file is auto-generated by @hey-api/openapi-ts

export type Format = 'raw' | 'oci' | 'maven' | 'conan';

export type OciTagList = {
    name: string;
    tags: Array<string>;
};

export type RawDirectoryEntry = {
    path: string;
    digest: string;
    size: number;
    contentType: string;
};

export type RawDirectoryPage = {
    path: string;
    items: Array<RawDirectoryEntry>;
};

export type OciError = {
    errors: Array<{
        code: string;
        message: string;
    }>;
};

export type Repository = {
    id: string;
    name: string;
    format: Format;
    state: 'active' | 'deleting' | 'deleted';
    version: string;
};

export type CreateRepository = {
    name: string;
    format: Format;
};

export type Group = {
    id: string;
    name: string;
    format: Format;
    members: MemberList;
    version: string;
};

export type CreateGroup = {
    name: string;
    format: Format;
    members: MemberList;
};

export type Member = {
    repositoryId: string;
    position: number;
};

export type MemberList = Array<Member>;

export type Grant = {
    principal: string;
    scopes: Array<'repositories:read' | 'repositories:write' | 'repositories:admin'>;
};

export type GrantList = Array<Grant>;

export type RetentionPolicy = {
    version: string;
    keepDays: number;
    minimumVersions: number;
};

export type RetentionDryRun = {
    policyVersion: string;
    candidates: Array<{
        coordinate: string;
        digest: string;
        createdAt: string;
    }>;
};

export type RestoreArtifact = {
    coordinate: string;
};

export type LifecycleJob = {
    id: string;
    kind: 'retention' | 'promotion' | 'replication' | 'reclaim';
    state: 'pending' | 'running' | 'completed' | 'failed';
    createdAt: string;
    startedAt?: string;
    completedAt?: string;
    lastError?: string;
};

export type ArtifactTombstone = {
    coordinate: string;
    digest: string;
    tombstonedAt: string;
};

export type ArtifactTombstonePage = {
    items: Array<ArtifactTombstone>;
    nextPageToken?: string;
};

/**
 * Maven-only management publish session. Raw Hosted writes use PUT /raw/{repository}/{path}; OCI Hosted writes use Registry V2 upload and manifest routes.
 */
export type CreatePublishSession = CreateMavenPublishSession;

export type CreateMavenPublishSession = {
    format: 'maven';
    coordinate: string;
    pomObject: string;
    objects: Array<DeclaredObject>;
};

/**
 * Expected names detect incomplete upload only. Digest, size, checksum, metadata, object keys, and visibility are derived and controlled by the Gateway.
 */
export type CommitMavenCoordinate = {
    expectedAssetNames: Array<string>;
};

export type DeclaredObject = {
    name: string;
    digest: string;
    size: number;
};

export type PublishSession = {
    id: string;
    repositoryId: string;
    coordinate: string;
    state: 'open' | 'committed' | 'aborted' | 'expired';
    expiresAt: string;
    objects: Array<DeclaredObject>;
};

export type Artifact = {
    id: string;
    coordinate: string;
    digest: string;
    createdAt: string;
    state: 'visible' | 'deleted';
};

export type Deletion = {
    id: string;
    state: 'pending';
};

export type Problem = {
    type: string;
    title: string;
    status: number;
    code: 'invalid_request' | 'invalid_page_token' | 'access_denied' | 'not_found' | 'version_conflict' | 'idempotency_conflict' | 'coordinate_exists' | 'session_closed' | 'digest_mismatch' | 'retention_protected' | 'internal_error';
    message: string;
    requestId: string;
};

export type RepositoryPage = {
    items: Array<Repository>;
    nextPageToken?: string;
};

export type GroupPage = {
    items: Array<Group>;
    nextPageToken?: string;
};

export type ArtifactPage = {
    items: Array<Artifact>;
    nextPageToken?: string;
};

export type AuditRecord = {
    groupName?: string;
    repository?: string;
    memberName?: string;
    outcome: string;
    actor?: string;
    occurredAt: string;
    format?: string;
    resource?: string;
    representation?: string;
    memberType?: string;
    upstreamHost?: string;
    operation?: string;
    status?: number;
    cacheDisposition?: string;
    bytes?: number;
    /**
     * Optional bounded authorization decision source. Current values include repository_grants, legacy_static, legacy_protocol, and administrator; consumers must accept future bounded values.
     */
    authorizationSource?: string;
    /**
     * Optional bounded authorization decision reason. Current values include scope_not_granted and grant_lookup_failed; consumers must accept future bounded values.
     */
    authorizationReason?: string;
    requestId?: string;
    traceId?: string;
};

export type AuditList = Array<AuditRecord>;

export type RepositoryCapabilities = {
    format: Format;
    type: 'hosted';
    operations: Array<'read' | 'publish' | 'browse' | 'delete' | 'restore' | 'retain' | 'reclaim'>;
};

export type ArtifactSummary = {
    coordinate: string;
    digest?: string;
    size?: number;
    contentType?: string;
    createdAt?: string;
};

export type ArtifactSummaryPage = {
    items: Array<ArtifactSummary>;
    nextPageToken?: string;
};

export type OciImage = {
    name: string;
};

export type OciImagePage = {
    items: Array<OciImage>;
    nextPageToken?: string;
};

export type MavenCoordinate = {
    coordinate: string;
    digest: string;
    createdAt: string;
};

export type MavenCoordinatePage = {
    items: Array<MavenCoordinate>;
    nextPageToken?: string;
};

export type ConanReference = {
    reference: string;
};

export type ConanReferencePage = {
    items: Array<ConanReference>;
    nextPageToken?: string;
};

export type RepositoryId = string;

export type GroupId = string;

export type SessionId = string;

export type RepositoryName = string;

/**
 * OCI repository name. The gateway resolves slash-separated OCI names without decoding encoded separators.
 */
export type OciName = string;

export type OciReference = string;

export type Digest = string;

export type PageSize = number;

export type PageToken = string;

export type IdempotencyKey = string;

export type IfMatch = string;

/**
 * OCI image-name prefix used to filter the repository projection.
 */
export type OciImagePrefix = string;

/**
 * Maven coordinate prefix used to filter the committed-coordinate projection.
 */
export type MavenCoordinatePrefix = string;

/**
 * Conan recipe-reference prefix used to filter the visible-reference projection.
 */
export type ConanReferencePrefix = string;

export type ListAuditsData = {
    body?: never;
    path?: never;
    query?: {
        group?: string;
        repository?: string;
        limit?: number;
    };
    url: '/audits';
};

export type ListAuditsErrors = {
    /**
     * Problem response
     */
    401: Problem;
};

export type ListAuditsError = ListAuditsErrors[keyof ListAuditsErrors];

export type ListAuditsResponses = {
    /**
     * Administrative audit records, ordered newest first
     */
    200: AuditList;
};

export type ListAuditsResponse = ListAuditsResponses[keyof ListAuditsResponses];

export type ListRepositoriesData = {
    body?: never;
    path?: never;
    query?: {
        pageSize?: number;
        pageToken?: string;
    };
    url: '/repositories';
};

export type ListRepositoriesErrors = {
    /**
     * Problem response
     */
    401: Problem;
};

export type ListRepositoriesError = ListRepositoriesErrors[keyof ListRepositoriesErrors];

export type ListRepositoriesResponses = {
    /**
     * Repository page
     */
    200: RepositoryPage;
};

export type ListRepositoriesResponse = ListRepositoriesResponses[keyof ListRepositoriesResponses];

export type CreateRepositoryData = {
    body: CreateRepository;
    headers: {
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/repositories';
};

export type CreateRepositoryErrors = {
    /**
     * Problem response
     */
    400: Problem;
    /**
     * Problem response
     */
    409: Problem;
};

export type CreateRepositoryError = CreateRepositoryErrors[keyof CreateRepositoryErrors];

export type CreateRepositoryResponses = {
    /**
     * Repository
     */
    201: Repository;
};

export type CreateRepositoryResponse = CreateRepositoryResponses[keyof CreateRepositoryResponses];

export type DeleteRepositoryData = {
    body?: never;
    path: {
        repositoryId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}';
};

export type DeleteRepositoryErrors = {
    /**
     * Problem response
     */
    409: Problem;
};

export type DeleteRepositoryError = DeleteRepositoryErrors[keyof DeleteRepositoryErrors];

export type DeleteRepositoryResponses = {
    /**
     * Accepted deletion
     */
    202: Deletion;
};

export type DeleteRepositoryResponse = DeleteRepositoryResponses[keyof DeleteRepositoryResponses];

export type GetRepositoryData = {
    body?: never;
    path: {
        repositoryId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}';
};

export type GetRepositoryErrors = {
    /**
     * Problem response
     */
    404: Problem;
};

export type GetRepositoryError = GetRepositoryErrors[keyof GetRepositoryErrors];

export type GetRepositoryResponses = {
    /**
     * Repository
     */
    200: Repository;
};

export type GetRepositoryResponse = GetRepositoryResponses[keyof GetRepositoryResponses];

export type ListGrantsData = {
    body?: never;
    path: {
        repositoryId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}/grants';
};

export type ListGrantsResponses = {
    /**
     * Grants
     */
    200: GrantList;
};

export type ListGrantsResponse = ListGrantsResponses[keyof ListGrantsResponses];

export type ReplaceGrantsData = {
    body: GrantList;
    headers: {
        'If-Match': string;
    };
    path: {
        repositoryId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}/grants';
};

export type ReplaceGrantsErrors = {
    /**
     * Problem response
     */
    412: Problem;
};

export type ReplaceGrantsError = ReplaceGrantsErrors[keyof ReplaceGrantsErrors];

export type ReplaceGrantsResponses = {
    /**
     * Grants
     */
    200: GrantList;
};

export type ReplaceGrantsResponse = ReplaceGrantsResponses[keyof ReplaceGrantsResponses];

export type GetRetentionPolicyData = {
    body?: never;
    path: {
        repositoryId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}/retention-policy';
};

export type GetRetentionPolicyResponses = {
    /**
     * Retention policy
     */
    200: RetentionPolicy;
};

export type GetRetentionPolicyResponse = GetRetentionPolicyResponses[keyof GetRetentionPolicyResponses];

export type ReplaceRetentionPolicyData = {
    body: RetentionPolicy;
    headers: {
        'If-Match': string;
    };
    path: {
        repositoryId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}/retention-policy';
};

export type ReplaceRetentionPolicyErrors = {
    /**
     * Problem response
     */
    412: Problem;
};

export type ReplaceRetentionPolicyError = ReplaceRetentionPolicyErrors[keyof ReplaceRetentionPolicyErrors];

export type ReplaceRetentionPolicyResponses = {
    /**
     * Retention policy
     */
    200: RetentionPolicy;
};

export type ReplaceRetentionPolicyResponse = ReplaceRetentionPolicyResponses[keyof ReplaceRetentionPolicyResponses];

export type DryRunRepositoryRetentionData = {
    body?: never;
    path: {
        repositoryId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}/retention:dry-run';
};

export type DryRunRepositoryRetentionResponses = {
    /**
     * Maven retention candidates without state changes
     */
    200: RetentionDryRun;
};

export type DryRunRepositoryRetentionResponse = DryRunRepositoryRetentionResponses[keyof DryRunRepositoryRetentionResponses];

export type ExecuteRepositoryRetentionData = {
    body?: never;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        repositoryId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}/retention:execute';
};

export type ExecuteRepositoryRetentionResponses = {
    /**
     * Maven retention job accepted
     */
    202: LifecycleJob;
};

export type ExecuteRepositoryRetentionResponse = ExecuteRepositoryRetentionResponses[keyof ExecuteRepositoryRetentionResponses];

export type RestoreRepositoryArtifactData = {
    body: RestoreArtifact;
    path: {
        repositoryId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}/restore';
};

export type RestoreRepositoryArtifactResponses = {
    /**
     * Tombstoned artifact restored
     */
    204: void;
};

export type RestoreRepositoryArtifactResponse = RestoreRepositoryArtifactResponses[keyof RestoreRepositoryArtifactResponses];

export type ListRepositoryLifecycleJobsData = {
    body?: never;
    path: {
        repositoryId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}/lifecycle-jobs';
};

export type ListRepositoryLifecycleJobsErrors = {
    /**
     * Problem response
     */
    403: Problem;
};

export type ListRepositoryLifecycleJobsError = ListRepositoryLifecycleJobsErrors[keyof ListRepositoryLifecycleJobsErrors];

export type ListRepositoryLifecycleJobsResponses = {
    /**
     * Lifecycle jobs for one repository, newest first
     */
    200: Array<LifecycleJob>;
};

export type ListRepositoryLifecycleJobsResponse = ListRepositoryLifecycleJobsResponses[keyof ListRepositoryLifecycleJobsResponses];

export type ListRepositoryTombstonesData = {
    body?: never;
    path: {
        repositoryId: string;
    };
    query?: {
        q?: string;
        pageSize?: number;
        pageToken?: string;
    };
    url: '/repositories/{repositoryId}/tombstones';
};

export type ListRepositoryTombstonesResponses = {
    /**
     * Tombstoned artifacts for one repository
     */
    200: ArtifactTombstonePage;
};

export type ListRepositoryTombstonesResponse = ListRepositoryTombstonesResponses[keyof ListRepositoryTombstonesResponses];

export type GetRepositoryCapabilitiesData = {
    body?: never;
    path: {
        repositoryId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}/capabilities';
};

export type GetRepositoryCapabilitiesErrors = {
    /**
     * Problem response
     */
    404: Problem;
};

export type GetRepositoryCapabilitiesError = GetRepositoryCapabilitiesErrors[keyof GetRepositoryCapabilitiesErrors];

export type GetRepositoryCapabilitiesResponses = {
    /**
     * Operations supported by a Hosted repository format
     */
    200: RepositoryCapabilities;
};

export type GetRepositoryCapabilitiesResponse = GetRepositoryCapabilitiesResponses[keyof GetRepositoryCapabilitiesResponses];

export type ListGroupsData = {
    body?: never;
    path?: never;
    query?: {
        pageSize?: number;
        pageToken?: string;
    };
    url: '/groups';
};

export type ListGroupsResponses = {
    /**
     * Group page
     */
    200: GroupPage;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type CreateGroupData = {
    body: CreateGroup;
    headers: {
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/groups';
};

export type CreateGroupErrors = {
    /**
     * Problem response
     */
    409: Problem;
};

export type CreateGroupError = CreateGroupErrors[keyof CreateGroupErrors];

export type CreateGroupResponses = {
    /**
     * Group
     */
    201: Group;
};

export type CreateGroupResponse = CreateGroupResponses[keyof CreateGroupResponses];

export type DeleteGroupData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}';
};

export type DeleteGroupResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteGroupResponse = DeleteGroupResponses[keyof DeleteGroupResponses];

export type GetGroupData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}';
};

export type GetGroupResponses = {
    /**
     * Group
     */
    200: Group;
};

export type GetGroupResponse = GetGroupResponses[keyof GetGroupResponses];

export type ReplaceGroupData = {
    body: Group;
    headers: {
        'If-Match': string;
    };
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}';
};

export type ReplaceGroupErrors = {
    /**
     * Problem response
     */
    412: Problem;
};

export type ReplaceGroupError = ReplaceGroupErrors[keyof ReplaceGroupErrors];

export type ReplaceGroupResponses = {
    /**
     * Group
     */
    200: Group;
};

export type ReplaceGroupResponse = ReplaceGroupResponses[keyof ReplaceGroupResponses];

export type ListGroupMembersData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}/members';
};

export type ListGroupMembersResponses = {
    /**
     * Members
     */
    200: MemberList;
};

export type ListGroupMembersResponse = ListGroupMembersResponses[keyof ListGroupMembersResponses];

export type ReplaceGroupMembersData = {
    body: MemberList;
    headers: {
        'If-Match': string;
    };
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}/members';
};

export type ReplaceGroupMembersErrors = {
    /**
     * Problem response
     */
    412: Problem;
};

export type ReplaceGroupMembersError = ReplaceGroupMembersErrors[keyof ReplaceGroupMembersErrors];

export type ReplaceGroupMembersResponses = {
    /**
     * Members
     */
    200: MemberList;
};

export type ReplaceGroupMembersResponse = ReplaceGroupMembersResponses[keyof ReplaceGroupMembersResponses];

export type CreatePublishSessionData = {
    body: CreatePublishSession;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        repositoryId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}/publish-sessions';
};

export type CreatePublishSessionErrors = {
    /**
     * Problem response
     */
    409: Problem;
};

export type CreatePublishSessionError = CreatePublishSessionErrors[keyof CreatePublishSessionErrors];

export type CreatePublishSessionResponses = {
    /**
     * Publish session
     */
    201: PublishSession;
};

export type CreatePublishSessionResponse = CreatePublishSessionResponses[keyof CreatePublishSessionResponses];

export type GetPublishSessionData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/publish-sessions/{sessionId}';
};

export type GetPublishSessionErrors = {
    /**
     * Problem response
     */
    404: Problem;
};

export type GetPublishSessionError = GetPublishSessionErrors[keyof GetPublishSessionErrors];

export type GetPublishSessionResponses = {
    /**
     * Publish session
     */
    200: PublishSession;
};

export type GetPublishSessionResponse = GetPublishSessionResponses[keyof GetPublishSessionResponses];

export type UploadPublishObjectData = {
    body: string;
    path: {
        sessionId: string;
        objectName: string;
    };
    query?: never;
    url: '/publish-sessions/{sessionId}/objects/{objectName}';
};

export type UploadPublishObjectErrors = {
    /**
     * Problem response
     */
    409: Problem;
    /**
     * Problem response
     */
    422: Problem;
};

export type UploadPublishObjectError = UploadPublishObjectErrors[keyof UploadPublishObjectErrors];

export type UploadPublishObjectResponses = {
    /**
     * Verified and staged
     */
    204: void;
};

export type UploadPublishObjectResponse = UploadPublishObjectResponses[keyof UploadPublishObjectResponses];

export type CommitPublishSessionData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/publish-sessions/{sessionId}:commit';
};

export type CommitPublishSessionErrors = {
    /**
     * Problem response
     */
    409: Problem;
    /**
     * Problem response
     */
    422: Problem;
};

export type CommitPublishSessionError = CommitPublishSessionErrors[keyof CommitPublishSessionErrors];

export type CommitPublishSessionResponses = {
    /**
     * Artifact
     */
    200: Artifact;
};

export type CommitPublishSessionResponse = CommitPublishSessionResponses[keyof CommitPublishSessionResponses];

export type ListArtifactsData = {
    body?: never;
    path: {
        repositoryId: string;
    };
    query?: {
        pageSize?: number;
        pageToken?: string;
    };
    url: '/repositories/{repositoryId}/artifacts';
};

export type ListArtifactsResponses = {
    /**
     * Artifact page
     */
    200: ArtifactPage;
};

export type ListArtifactsResponse = ListArtifactsResponses[keyof ListArtifactsResponses];

export type SearchRepositoryArtifactsData = {
    body?: never;
    path: {
        repositoryId: string;
    };
    query?: {
        q?: string;
        pageSize?: number;
        pageToken?: string;
    };
    url: '/repositories/{repositoryId}/artifact-search';
};

export type SearchRepositoryArtifactsErrors = {
    /**
     * Problem response
     */
    400: Problem;
};

export type SearchRepositoryArtifactsError = SearchRepositoryArtifactsErrors[keyof SearchRepositoryArtifactsErrors];

export type SearchRepositoryArtifactsResponses = {
    /**
     * Format-aware artifact browse/search page
     */
    200: ArtifactSummaryPage;
};

export type SearchRepositoryArtifactsResponse = SearchRepositoryArtifactsResponses[keyof SearchRepositoryArtifactsResponses];

export type DeleteArtifactData = {
    body?: never;
    path: {
        repositoryId: string;
        artifactId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}/artifacts/{artifactId}';
};

export type DeleteArtifactResponses = {
    /**
     * Accepted deletion
     */
    202: Deletion;
};

export type DeleteArtifactResponse = DeleteArtifactResponses[keyof DeleteArtifactResponses];

export type GetArtifactData = {
    body?: never;
    path: {
        repositoryId: string;
        artifactId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}/artifacts/{artifactId}';
};

export type GetArtifactResponses = {
    /**
     * Artifact
     */
    200: Artifact;
};

export type GetArtifactResponse = GetArtifactResponses[keyof GetArtifactResponses];

export type ListOciImagesData = {
    body?: never;
    path: {
        repositoryId: string;
    };
    query?: {
        /**
         * OCI image-name prefix used to filter the repository projection.
         */
        q?: string;
        pageSize?: number;
        pageToken?: string;
    };
    url: '/repositories/{repositoryId}/oci/images';
};

export type ListOciImagesErrors = {
    /**
     * Problem response
     */
    400: Problem;
    /**
     * Problem response
     */
    404: Problem;
};

export type ListOciImagesError = ListOciImagesErrors[keyof ListOciImagesErrors];

export type ListOciImagesResponses = {
    /**
     * OCI image-name projection page
     */
    200: OciImagePage;
};

export type ListOciImagesResponse = ListOciImagesResponses[keyof ListOciImagesResponses];

export type ListMavenCoordinatesData = {
    body?: never;
    path: {
        repositoryId: string;
    };
    query?: {
        /**
         * Maven coordinate prefix used to filter the committed-coordinate projection.
         */
        q?: string;
        pageSize?: number;
        pageToken?: string;
    };
    url: '/repositories/{repositoryId}/maven/coordinates';
};

export type ListMavenCoordinatesErrors = {
    /**
     * Problem response
     */
    400: Problem;
    /**
     * Problem response
     */
    404: Problem;
};

export type ListMavenCoordinatesError = ListMavenCoordinatesErrors[keyof ListMavenCoordinatesErrors];

export type ListMavenCoordinatesResponses = {
    /**
     * Maven committed-coordinate projection page
     */
    200: MavenCoordinatePage;
};

export type ListMavenCoordinatesResponse = ListMavenCoordinatesResponses[keyof ListMavenCoordinatesResponses];

export type ListConanReferencesData = {
    body?: never;
    path: {
        repositoryId: string;
    };
    query?: {
        /**
         * Conan recipe-reference prefix used to filter the visible-reference projection.
         */
        q?: string;
        pageSize?: number;
        pageToken?: string;
    };
    url: '/repositories/{repositoryId}/conan/references';
};

export type ListConanReferencesErrors = {
    /**
     * Problem response
     */
    400: Problem;
    /**
     * Problem response
     */
    404: Problem;
};

export type ListConanReferencesError = ListConanReferencesErrors[keyof ListConanReferencesErrors];

export type ListConanReferencesResponses = {
    /**
     * Conan visible recipe-reference projection page
     */
    200: ConanReferencePage;
};

export type ListConanReferencesResponse = ListConanReferencesResponses[keyof ListConanReferencesResponses];

export type DeleteRawHostedContentData = {
    body?: never;
    path: {
        repository: string;
        /**
         * Canonical Raw path. This is a gateway catch-all parameter and may contain one or more slash-separated segments; empty, dot, dot-dot, and percent-encoded segments are rejected.
         */
        path: string;
    };
    query?: {
        uploadId?: string;
    };
    url: '/raw/{repository}/{path}';
};

export type DeleteRawHostedContentErrors = {
    /**
     * Raw or Maven Basic authentication required when anonymous read policy is disabled
     */
    401: unknown;
    /**
     * No committed object is addressable at this protocol path
     */
    404: unknown;
};

export type DeleteRawHostedContentResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteRawHostedContentResponse = DeleteRawHostedContentResponses[keyof DeleteRawHostedContentResponses];

export type ReadRawContentData = {
    body?: never;
    path: {
        repository: string;
        /**
         * Canonical Raw path. This is a gateway catch-all parameter and may contain one or more slash-separated segments; empty, dot, dot-dot, and percent-encoded segments are rejected.
         */
        path: string;
    };
    query?: {
        uploadId?: string;
    };
    url: '/raw/{repository}/{path}';
};

export type ReadRawContentErrors = {
    /**
     * Raw or Maven Basic authentication required when anonymous read policy is disabled
     */
    401: unknown;
    /**
     * No committed object is addressable at this protocol path
     */
    404: unknown;
};

export type ReadRawContentResponses = {
    /**
     * Raw bytes or a Raw directory-prefix JSON page
     */
    200: unknown;
};

export type HeadRawContentData = {
    body?: never;
    path: {
        repository: string;
        /**
         * Canonical Raw path. This is a gateway catch-all parameter and may contain one or more slash-separated segments; empty, dot, dot-dot, and percent-encoded segments are rejected.
         */
        path: string;
    };
    query?: never;
    url: '/raw/{repository}/{path}';
};

export type HeadRawContentErrors = {
    /**
     * Raw or Maven Basic authentication required when anonymous read policy is disabled
     */
    401: unknown;
    /**
     * No committed object is addressable at this protocol path
     */
    404: unknown;
};

export type HeadRawContentResponses = {
    /**
     * Committed immutable protocol object
     */
    200: Blob | File;
};

export type HeadRawContentResponse = HeadRawContentResponses[keyof HeadRawContentResponses];

export type AppendRawHostedResumableUploadData = {
    body: string;
    headers: {
        'Upload-Offset': number;
    };
    path: {
        repository: string;
        /**
         * Canonical Raw path. This is a gateway catch-all parameter and may contain one or more slash-separated segments; empty, dot, dot-dot, and percent-encoded segments are rejected.
         */
        path: string;
    };
    query: {
        uploadId: string;
    };
    url: '/raw/{repository}/{path}';
};

export type AppendRawHostedResumableUploadErrors = {
    /**
     * Raw or Maven Basic authentication required when anonymous read policy is disabled
     */
    401: unknown;
    /**
     * No committed object is addressable at this protocol path
     */
    404: unknown;
    /**
     * Problem response
     */
    409: Problem;
};

export type AppendRawHostedResumableUploadError = AppendRawHostedResumableUploadErrors[keyof AppendRawHostedResumableUploadErrors];

export type AppendRawHostedResumableUploadResponses = {
    /**
     * Bytes appended
     */
    204: void;
};

export type AppendRawHostedResumableUploadResponse = AppendRawHostedResumableUploadResponses[keyof AppendRawHostedResumableUploadResponses];

export type StartRawHostedResumableUploadData = {
    body?: never;
    path: {
        repository: string;
        /**
         * Canonical Raw path. This is a gateway catch-all parameter and may contain one or more slash-separated segments; empty, dot, dot-dot, and percent-encoded segments are rejected.
         */
        path: string;
    };
    query: {
        resumable: '1';
    };
    url: '/raw/{repository}/{path}';
};

export type StartRawHostedResumableUploadErrors = {
    /**
     * Raw or Maven Basic authentication required when anonymous read policy is disabled
     */
    401: unknown;
};

export type StartRawHostedResumableUploadResponses = {
    /**
     * Upload session created
     */
    201: unknown;
};

export type PutRawHostedContentData = {
    body: string;
    headers?: {
        'Upload-Offset'?: number;
        Digest?: string;
    };
    path: {
        repository: string;
        /**
         * Canonical Raw path. This is a gateway catch-all parameter and may contain one or more slash-separated segments; empty, dot, dot-dot, and percent-encoded segments are rejected.
         */
        path: string;
    };
    query?: {
        uploadId?: string;
        complete?: '1';
    };
    url: '/raw/{repository}/{path}';
};

export type PutRawHostedContentErrors = {
    /**
     * Raw or Maven Basic authentication required when anonymous read policy is disabled
     */
    401: unknown;
    /**
     * Problem response
     */
    422: Problem;
};

export type PutRawHostedContentError = PutRawHostedContentErrors[keyof PutRawHostedContentErrors];

export type PutRawHostedContentResponses = {
    /**
     * Stored and immediately addressable at this Raw path
     */
    201: unknown;
};

export type ListRawRootDirectoryData = {
    body?: never;
    path: {
        repository: string;
    };
    query?: {
        n?: number;
        last?: string;
    };
    url: '/raw/{repository}/';
};

export type ListRawRootDirectoryErrors = {
    /**
     * Raw or Maven Basic authentication required when anonymous read policy is disabled
     */
    401: unknown;
};

export type ListRawRootDirectoryResponses = {
    /**
     * Lexicographically ordered Native Raw directory-prefix page
     */
    200: RawDirectoryPage;
};

export type ListRawRootDirectoryResponse = ListRawRootDirectoryResponses[keyof ListRawRootDirectoryResponses];

export type StartOciUploadData = {
    body?: never;
    path: {
        /**
         * OCI repository name. The gateway resolves slash-separated OCI names without decoding encoded separators.
         */
        name: string;
    };
    query?: {
        mount?: string;
        from?: string;
    };
    url: '/v2/{name}/blobs/uploads/';
};

export type StartOciUploadErrors = {
    /**
     * OCI Registry error response
     */
    400: OciError;
    /**
     * OCI Bearer authentication challenge
     */
    401: unknown;
};

export type StartOciUploadError = StartOciUploadErrors[keyof StartOciUploadErrors];

export type StartOciUploadResponses = {
    /**
     * Blob mounted
     */
    201: unknown;
    /**
     * Registry V2 upload in progress
     */
    202: unknown;
};

export type CancelOciUploadData = {
    body?: never;
    path: {
        /**
         * OCI repository name. The gateway resolves slash-separated OCI names without decoding encoded separators.
         */
        name: string;
        uuid: string;
    };
    query?: never;
    url: '/v2/{name}/blobs/uploads/{uuid}';
};

export type CancelOciUploadErrors = {
    /**
     * OCI Bearer authentication challenge
     */
    401: unknown;
    /**
     * OCI Registry error response
     */
    404: OciError;
};

export type CancelOciUploadError = CancelOciUploadErrors[keyof CancelOciUploadErrors];

export type CancelOciUploadResponses = {
    /**
     * Upload cancelled
     */
    204: void;
};

export type CancelOciUploadResponse = CancelOciUploadResponses[keyof CancelOciUploadResponses];

export type GetOciUploadStatusData = {
    body?: never;
    path: {
        /**
         * OCI repository name. The gateway resolves slash-separated OCI names without decoding encoded separators.
         */
        name: string;
        uuid: string;
    };
    query?: never;
    url: '/v2/{name}/blobs/uploads/{uuid}';
};

export type GetOciUploadStatusErrors = {
    /**
     * OCI Bearer authentication challenge
     */
    401: unknown;
    /**
     * OCI Registry error response
     */
    404: OciError;
};

export type GetOciUploadStatusError = GetOciUploadStatusErrors[keyof GetOciUploadStatusErrors];

export type GetOciUploadStatusResponses = {
    /**
     * Registry V2 upload in progress
     */
    204: void;
};

export type GetOciUploadStatusResponse = GetOciUploadStatusResponses[keyof GetOciUploadStatusResponses];

export type AppendOciUploadData = {
    body: string;
    path: {
        /**
         * OCI repository name. The gateway resolves slash-separated OCI names without decoding encoded separators.
         */
        name: string;
        uuid: string;
    };
    query?: never;
    url: '/v2/{name}/blobs/uploads/{uuid}';
};

export type AppendOciUploadErrors = {
    /**
     * OCI Bearer authentication challenge
     */
    401: unknown;
    /**
     * OCI Registry error response
     */
    404: OciError;
    /**
     * OCI Registry error response
     */
    416: OciError;
};

export type AppendOciUploadError = AppendOciUploadErrors[keyof AppendOciUploadErrors];

export type AppendOciUploadResponses = {
    /**
     * Registry V2 upload in progress
     */
    202: unknown;
};

export type CompleteOciUploadData = {
    body?: string;
    path: {
        /**
         * OCI repository name. The gateway resolves slash-separated OCI names without decoding encoded separators.
         */
        name: string;
        uuid: string;
    };
    query: {
        digest: string;
    };
    url: '/v2/{name}/blobs/uploads/{uuid}';
};

export type CompleteOciUploadErrors = {
    /**
     * OCI Registry error response
     */
    400: OciError;
    /**
     * OCI Bearer authentication challenge
     */
    401: unknown;
    /**
     * OCI Registry error response
     */
    404: OciError;
    /**
     * OCI Registry error response
     */
    409: OciError;
    /**
     * OCI Registry error response
     */
    416: OciError;
};

export type CompleteOciUploadError = CompleteOciUploadErrors[keyof CompleteOciUploadErrors];

export type CompleteOciUploadResponses = {
    /**
     * Blob completed
     */
    201: unknown;
};

export type ReadOciBlobData = {
    body?: never;
    path: {
        /**
         * OCI repository name. The gateway resolves slash-separated OCI names without decoding encoded separators.
         */
        name: string;
        digest: string;
    };
    query?: never;
    url: '/v2/{name}/blobs/{digest}';
};

export type ReadOciBlobErrors = {
    /**
     * OCI Bearer authentication challenge
     */
    401: unknown;
    /**
     * No committed object is addressable at this protocol path
     */
    404: unknown;
};

export type ReadOciBlobResponses = {
    /**
     * Committed immutable protocol object
     */
    200: Blob | File;
};

export type ReadOciBlobResponse = ReadOciBlobResponses[keyof ReadOciBlobResponses];

export type HeadOciBlobData = {
    body?: never;
    path: {
        /**
         * OCI repository name. The gateway resolves slash-separated OCI names without decoding encoded separators.
         */
        name: string;
        digest: string;
    };
    query?: never;
    url: '/v2/{name}/blobs/{digest}';
};

export type HeadOciBlobErrors = {
    /**
     * OCI Bearer authentication challenge
     */
    401: unknown;
    /**
     * No committed object is addressable at this protocol path
     */
    404: unknown;
};

export type HeadOciBlobResponses = {
    /**
     * Committed immutable protocol object
     */
    200: Blob | File;
};

export type HeadOciBlobResponse = HeadOciBlobResponses[keyof HeadOciBlobResponses];

export type DeleteOciManifestData = {
    body?: never;
    path: {
        /**
         * OCI repository name. The gateway resolves slash-separated OCI names without decoding encoded separators.
         */
        name: string;
        reference: string;
    };
    query?: never;
    url: '/v2/{name}/manifests/{reference}';
};

export type DeleteOciManifestErrors = {
    /**
     * OCI Registry error response
     */
    400: OciError;
    /**
     * OCI Bearer authentication challenge
     */
    401: unknown;
    /**
     * OCI Registry error response
     */
    404: OciError;
};

export type DeleteOciManifestError = DeleteOciManifestErrors[keyof DeleteOciManifestErrors];

export type DeleteOciManifestResponses = {
    /**
     * Manifest deleted
     */
    202: unknown;
};

export type ReadOciManifestData = {
    body?: never;
    path: {
        /**
         * OCI repository name. The gateway resolves slash-separated OCI names without decoding encoded separators.
         */
        name: string;
        reference: string;
    };
    query?: never;
    url: '/v2/{name}/manifests/{reference}';
};

export type ReadOciManifestErrors = {
    /**
     * OCI Bearer authentication challenge
     */
    401: unknown;
    /**
     * No committed object is addressable at this protocol path
     */
    404: unknown;
    /**
     * OCI Registry error response
     */
    406: OciError;
};

export type ReadOciManifestError = ReadOciManifestErrors[keyof ReadOciManifestErrors];

export type ReadOciManifestResponses = {
    /**
     * Committed OCI manifest, returned with Docker-Content-Digest
     */
    200: {
        [key: string]: unknown;
    };
};

export type ReadOciManifestResponse = ReadOciManifestResponses[keyof ReadOciManifestResponses];

export type HeadOciManifestData = {
    body?: never;
    path: {
        /**
         * OCI repository name. The gateway resolves slash-separated OCI names without decoding encoded separators.
         */
        name: string;
        reference: string;
    };
    query?: never;
    url: '/v2/{name}/manifests/{reference}';
};

export type HeadOciManifestErrors = {
    /**
     * OCI Bearer authentication challenge
     */
    401: unknown;
    /**
     * No committed object is addressable at this protocol path
     */
    404: unknown;
    /**
     * OCI Registry error response
     */
    406: OciError;
};

export type HeadOciManifestError = HeadOciManifestErrors[keyof HeadOciManifestErrors];

export type HeadOciManifestResponses = {
    /**
     * Committed OCI manifest, returned with Docker-Content-Digest
     */
    200: {
        [key: string]: unknown;
    };
};

export type HeadOciManifestResponse = HeadOciManifestResponses[keyof HeadOciManifestResponses];

export type PutOciManifestData = {
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * OCI repository name. The gateway resolves slash-separated OCI names without decoding encoded separators.
         */
        name: string;
        reference: string;
    };
    query?: never;
    url: '/v2/{name}/manifests/{reference}';
};

export type PutOciManifestErrors = {
    /**
     * OCI Registry error response
     */
    400: OciError;
    /**
     * OCI Bearer authentication challenge
     */
    401: unknown;
    /**
     * OCI Registry error response
     */
    413: OciError;
};

export type PutOciManifestError = PutOciManifestErrors[keyof PutOciManifestErrors];

export type PutOciManifestResponses = {
    /**
     * Manifest published
     */
    201: unknown;
};

export type ListOciTagsData = {
    body?: never;
    path: {
        /**
         * OCI repository name. The gateway resolves slash-separated OCI names without decoding encoded separators.
         */
        name: string;
    };
    query?: {
        n?: number;
        last?: string;
    };
    url: '/v2/{name}/tags/list';
};

export type ListOciTagsErrors = {
    /**
     * OCI Registry error response
     */
    400: OciError;
    /**
     * OCI Bearer authentication challenge
     */
    401: unknown;
    /**
     * No committed object is addressable at this protocol path
     */
    404: unknown;
};

export type ListOciTagsError = ListOciTagsErrors[keyof ListOciTagsErrors];

export type ListOciTagsResponses = {
    /**
     * OCI tag list ordered lexicographically. A Link header with rel=next is returned when more tags are available.
     */
    200: OciTagList;
};

export type ListOciTagsResponse = ListOciTagsResponses[keyof ListOciTagsResponses];

export type HeadOciTagsData = {
    body?: never;
    path: {
        /**
         * OCI repository name. The gateway resolves slash-separated OCI names without decoding encoded separators.
         */
        name: string;
    };
    query?: {
        n?: number;
        last?: string;
    };
    url: '/v2/{name}/tags/list';
};

export type HeadOciTagsErrors = {
    /**
     * OCI Registry error response
     */
    400: OciError;
    /**
     * OCI Bearer authentication challenge
     */
    401: unknown;
    /**
     * No committed object is addressable at this protocol path
     */
    404: unknown;
};

export type HeadOciTagsError = HeadOciTagsErrors[keyof HeadOciTagsErrors];

export type HeadOciTagsResponses = {
    /**
     * OCI tag list ordered lexicographically. A Link header with rel=next is returned when more tags are available.
     */
    200: OciTagList;
};

export type HeadOciTagsResponse = HeadOciTagsResponses[keyof HeadOciTagsResponses];

export type ReadMavenAssetData = {
    body?: never;
    path: {
        repository: string;
        /**
         * Canonical Maven asset path: groupId path, artifactId, version, and filename. This is a gateway catch-all parameter; only committed POMs, component assets, checksums, and generated metadata are readable.
         */
        assetPath: string;
    };
    query?: never;
    url: '/repository/maven/{repository}/{assetPath}';
};

export type ReadMavenAssetErrors = {
    /**
     * Raw or Maven Basic authentication required when anonymous read policy is disabled
     */
    401: unknown;
    /**
     * No committed object is addressable at this protocol path
     */
    404: unknown;
};

export type ReadMavenAssetResponses = {
    /**
     * Committed immutable protocol object
     */
    200: Blob | File;
};

export type ReadMavenAssetResponse = ReadMavenAssetResponses[keyof ReadMavenAssetResponses];

export type StageMavenProtocolAssetData = {
    body: string;
    path: {
        repository: string;
        /**
         * Canonical Maven asset path: groupId path, artifactId, version, and filename. This is a gateway catch-all parameter; only committed POMs, component assets, checksums, and generated metadata are readable.
         */
        assetPath: string;
    };
    query?: never;
    url: '/repository/maven/{repository}/{assetPath}';
};

export type StageMavenProtocolAssetErrors = {
    /**
     * Raw or Maven Basic authentication required when anonymous read policy is disabled
     */
    401: unknown;
    /**
     * Problem response
     */
    409: Problem;
    /**
     * Problem response
     */
    422: Problem;
};

export type StageMavenProtocolAssetError = StageMavenProtocolAssetErrors[keyof StageMavenProtocolAssetErrors];

export type StageMavenProtocolAssetResponses = {
    /**
     * Staged or idempotently replayed; not readable until coordinate commit
     */
    201: unknown;
};

export type CommitMavenCoordinateData = {
    body: CommitMavenCoordinate;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        repository: string;
        coordinate: string;
    };
    query?: never;
    url: '/repository/maven/{repository}/coordinates/{coordinate}:commit';
};

export type CommitMavenCoordinateErrors = {
    /**
     * Problem response
     */
    409: Problem;
    /**
     * Problem response
     */
    422: Problem;
};

export type CommitMavenCoordinateError = CommitMavenCoordinateErrors[keyof CommitMavenCoordinateErrors];

export type CommitMavenCoordinateResponses = {
    /**
     * Artifact
     */
    200: Artifact;
};

export type CommitMavenCoordinateResponse = CommitMavenCoordinateResponses[keyof CommitMavenCoordinateResponses];

export type ClientOptions = {
    baseUrl: 'https://gateway.example.com/api/v2' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | (string & {});
};