// This file is auto-generated by @hey-api/openapi-ts

export type Format = 'raw' | 'oci' | 'maven';

export type Repository = {
    id: string;
    name: string;
    format: Format;
    state: 'active' | 'deleting' | 'deleted';
    version: string;
};

export type CreateRepository = {
    name: string;
    format: Format;
};

export type Group = {
    id: string;
    name: string;
    format: Format;
    members: MemberList;
    version: string;
};

export type CreateGroup = {
    name: string;
    format: Format;
    members: MemberList;
};

export type Member = {
    repositoryId: string;
    position: number;
};

export type MemberList = Array<Member>;

export type Grant = {
    principal: string;
    scopes: Array<'repositories:read' | 'repositories:write' | 'repositories:admin'>;
};

export type GrantList = Array<Grant>;

export type RetentionPolicy = {
    version: string;
    keepDays: number;
    minimumVersions: number;
};

export type CreatePublishSession = CreateRawPublishSession | CreateOciPublishSession | CreateMavenPublishSession;

export type CreateRawPublishSession = {
    format: 'raw';
    /**
     * Canonical multi-segment Raw path.
     */
    coordinate: string;
    objects: Array<DeclaredObject>;
};

export type CreateOciPublishSession = {
    format: 'oci';
    manifestDigest: string;
    tag?: string;
    objects: Array<DeclaredObject>;
};

export type CreateMavenPublishSession = {
    format: 'maven';
    coordinate: string;
    pomObject: string;
    objects: Array<DeclaredObject>;
};

export type DeclaredObject = {
    name: string;
    digest: string;
    size: number;
};

export type PublishSession = {
    id: string;
    repositoryId: string;
    coordinate: string;
    state: 'open' | 'committed' | 'aborted' | 'expired';
    expiresAt: string;
    objects: Array<DeclaredObject>;
};

export type Artifact = {
    id: string;
    coordinate: string;
    digest: string;
    createdAt: string;
    state: 'visible' | 'deleted';
};

export type Deletion = {
    id: string;
    state: 'pending';
};

export type Problem = {
    type: string;
    title: string;
    status: number;
    code: 'invalid_request' | 'invalid_page_token' | 'access_denied' | 'not_found' | 'version_conflict' | 'idempotency_conflict' | 'coordinate_exists' | 'session_closed' | 'digest_mismatch' | 'retention_protected' | 'internal_error';
    message: string;
    requestId: string;
};

export type RepositoryPage = {
    items: Array<Repository>;
    nextPageToken?: string;
};

export type GroupPage = {
    items: Array<Group>;
    nextPageToken?: string;
};

export type ArtifactPage = {
    items: Array<Artifact>;
    nextPageToken?: string;
};

export type RepositoryId = string;

export type GroupId = string;

export type SessionId = string;

export type RepositoryName = string;

/**
 * OCI repository name. The gateway resolves slash-separated OCI names without decoding encoded separators.
 */
export type OciName = string;

export type OciReference = string;

export type Digest = string;

export type PageSize = number;

export type PageToken = string;

export type IdempotencyKey = string;

export type IfMatch = string;

export type ListRepositoriesData = {
    body?: never;
    path?: never;
    query?: {
        pageSize?: number;
        pageToken?: string;
    };
    url: '/repositories';
};

export type ListRepositoriesErrors = {
    /**
     * Problem response
     */
    401: Problem;
};

export type ListRepositoriesError = ListRepositoriesErrors[keyof ListRepositoriesErrors];

export type ListRepositoriesResponses = {
    /**
     * Repository page
     */
    200: RepositoryPage;
};

export type ListRepositoriesResponse = ListRepositoriesResponses[keyof ListRepositoriesResponses];

export type CreateRepositoryData = {
    body: CreateRepository;
    headers: {
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/repositories';
};

export type CreateRepositoryErrors = {
    /**
     * Problem response
     */
    400: Problem;
    /**
     * Problem response
     */
    409: Problem;
};

export type CreateRepositoryError = CreateRepositoryErrors[keyof CreateRepositoryErrors];

export type CreateRepositoryResponses = {
    /**
     * Repository
     */
    201: Repository;
};

export type CreateRepositoryResponse = CreateRepositoryResponses[keyof CreateRepositoryResponses];

export type DeleteRepositoryData = {
    body?: never;
    path: {
        repositoryId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}';
};

export type DeleteRepositoryErrors = {
    /**
     * Problem response
     */
    409: Problem;
};

export type DeleteRepositoryError = DeleteRepositoryErrors[keyof DeleteRepositoryErrors];

export type DeleteRepositoryResponses = {
    /**
     * Accepted deletion
     */
    202: Deletion;
};

export type DeleteRepositoryResponse = DeleteRepositoryResponses[keyof DeleteRepositoryResponses];

export type GetRepositoryData = {
    body?: never;
    path: {
        repositoryId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}';
};

export type GetRepositoryErrors = {
    /**
     * Problem response
     */
    404: Problem;
};

export type GetRepositoryError = GetRepositoryErrors[keyof GetRepositoryErrors];

export type GetRepositoryResponses = {
    /**
     * Repository
     */
    200: Repository;
};

export type GetRepositoryResponse = GetRepositoryResponses[keyof GetRepositoryResponses];

export type ListGroupMembersData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}/members';
};

export type ListGroupMembersResponses = {
    /**
     * Members
     */
    200: MemberList;
};

export type ListGroupMembersResponse = ListGroupMembersResponses[keyof ListGroupMembersResponses];

export type ReplaceGroupMembersData = {
    body: MemberList;
    headers: {
        'If-Match': string;
    };
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}/members';
};

export type ReplaceGroupMembersErrors = {
    /**
     * Problem response
     */
    412: Problem;
};

export type ReplaceGroupMembersError = ReplaceGroupMembersErrors[keyof ReplaceGroupMembersErrors];

export type ReplaceGroupMembersResponses = {
    /**
     * Members
     */
    200: MemberList;
};

export type ReplaceGroupMembersResponse = ReplaceGroupMembersResponses[keyof ReplaceGroupMembersResponses];

export type ListGrantsData = {
    body?: never;
    path: {
        repositoryId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}/grants';
};

export type ListGrantsResponses = {
    /**
     * Grants
     */
    200: GrantList;
};

export type ListGrantsResponse = ListGrantsResponses[keyof ListGrantsResponses];

export type ReplaceGrantsData = {
    body: GrantList;
    headers: {
        'If-Match': string;
    };
    path: {
        repositoryId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}/grants';
};

export type ReplaceGrantsErrors = {
    /**
     * Problem response
     */
    412: Problem;
};

export type ReplaceGrantsError = ReplaceGrantsErrors[keyof ReplaceGrantsErrors];

export type ReplaceGrantsResponses = {
    /**
     * Grants
     */
    200: GrantList;
};

export type ReplaceGrantsResponse = ReplaceGrantsResponses[keyof ReplaceGrantsResponses];

export type GetRetentionPolicyData = {
    body?: never;
    path: {
        repositoryId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}/retention-policy';
};

export type GetRetentionPolicyResponses = {
    /**
     * Retention policy
     */
    200: RetentionPolicy;
};

export type GetRetentionPolicyResponse = GetRetentionPolicyResponses[keyof GetRetentionPolicyResponses];

export type ReplaceRetentionPolicyData = {
    body: RetentionPolicy;
    headers: {
        'If-Match': string;
    };
    path: {
        repositoryId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}/retention-policy';
};

export type ReplaceRetentionPolicyErrors = {
    /**
     * Problem response
     */
    412: Problem;
};

export type ReplaceRetentionPolicyError = ReplaceRetentionPolicyErrors[keyof ReplaceRetentionPolicyErrors];

export type ReplaceRetentionPolicyResponses = {
    /**
     * Retention policy
     */
    200: RetentionPolicy;
};

export type ReplaceRetentionPolicyResponse = ReplaceRetentionPolicyResponses[keyof ReplaceRetentionPolicyResponses];

export type ListGroupsData = {
    body?: never;
    path?: never;
    query?: {
        pageSize?: number;
        pageToken?: string;
    };
    url: '/groups';
};

export type ListGroupsResponses = {
    /**
     * Group page
     */
    200: GroupPage;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type CreateGroupData = {
    body: CreateGroup;
    headers: {
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/groups';
};

export type CreateGroupErrors = {
    /**
     * Problem response
     */
    409: Problem;
};

export type CreateGroupError = CreateGroupErrors[keyof CreateGroupErrors];

export type CreateGroupResponses = {
    /**
     * Group
     */
    201: Group;
};

export type CreateGroupResponse = CreateGroupResponses[keyof CreateGroupResponses];

export type DeleteGroupData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}';
};

export type DeleteGroupResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteGroupResponse = DeleteGroupResponses[keyof DeleteGroupResponses];

export type GetGroupData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}';
};

export type GetGroupResponses = {
    /**
     * Group
     */
    200: Group;
};

export type GetGroupResponse = GetGroupResponses[keyof GetGroupResponses];

export type ReplaceGroupData = {
    body: Group;
    headers: {
        'If-Match': string;
    };
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}';
};

export type ReplaceGroupErrors = {
    /**
     * Problem response
     */
    412: Problem;
};

export type ReplaceGroupError = ReplaceGroupErrors[keyof ReplaceGroupErrors];

export type ReplaceGroupResponses = {
    /**
     * Group
     */
    200: Group;
};

export type ReplaceGroupResponse = ReplaceGroupResponses[keyof ReplaceGroupResponses];

export type ReadRawContentData = {
    body?: never;
    path: {
        repository: string;
        /**
         * Canonical Raw path. This is a gateway catch-all parameter and may contain one or more slash-separated segments; empty, dot, dot-dot, and percent-encoded segments are rejected.
         */
        path: string;
    };
    query?: never;
    url: '/raw/{repository}/content/{path}';
};

export type ReadRawContentErrors = {
    /**
     * Raw or Maven Basic authentication required when anonymous read policy is disabled
     */
    401: unknown;
    /**
     * No committed object is addressable at this protocol path
     */
    404: unknown;
};

export type ReadRawContentResponses = {
    /**
     * Committed immutable protocol object
     */
    200: Blob | File;
};

export type ReadRawContentResponse = ReadRawContentResponses[keyof ReadRawContentResponses];

export type ReadOciManifestData = {
    body?: never;
    path: {
        /**
         * OCI repository name. The gateway resolves slash-separated OCI names without decoding encoded separators.
         */
        name: string;
        reference: string;
    };
    query?: never;
    url: '/v2/{name}/manifests/{reference}';
};

export type ReadOciManifestErrors = {
    /**
     * OCI Bearer authentication challenge
     */
    401: unknown;
    /**
     * No committed object is addressable at this protocol path
     */
    404: unknown;
};

export type ReadOciManifestResponses = {
    /**
     * Committed OCI manifest, returned with Docker-Content-Digest
     */
    200: {
        [key: string]: unknown;
    };
};

export type ReadOciManifestResponse = ReadOciManifestResponses[keyof ReadOciManifestResponses];

export type ReadOciBlobData = {
    body?: never;
    path: {
        /**
         * OCI repository name. The gateway resolves slash-separated OCI names without decoding encoded separators.
         */
        name: string;
        digest: string;
    };
    query?: never;
    url: '/v2/{name}/blobs/{digest}';
};

export type ReadOciBlobErrors = {
    /**
     * OCI Bearer authentication challenge
     */
    401: unknown;
    /**
     * No committed object is addressable at this protocol path
     */
    404: unknown;
};

export type ReadOciBlobResponses = {
    /**
     * Committed immutable protocol object
     */
    200: Blob | File;
};

export type ReadOciBlobResponse = ReadOciBlobResponses[keyof ReadOciBlobResponses];

export type ReadMavenAssetData = {
    body?: never;
    path: {
        repository: string;
        /**
         * Canonical Maven asset path: groupId path, artifactId, version, and filename. This is a gateway catch-all parameter; only committed POMs, component assets, checksums, and generated metadata are readable.
         */
        assetPath: string;
    };
    query?: never;
    url: '/repository/maven/{repository}/{assetPath}';
};

export type ReadMavenAssetErrors = {
    /**
     * Raw or Maven Basic authentication required when anonymous read policy is disabled
     */
    401: unknown;
    /**
     * No committed object is addressable at this protocol path
     */
    404: unknown;
};

export type ReadMavenAssetResponses = {
    /**
     * Committed immutable protocol object
     */
    200: Blob | File;
};

export type ReadMavenAssetResponse = ReadMavenAssetResponses[keyof ReadMavenAssetResponses];

export type CreatePublishSessionData = {
    body: CreatePublishSession;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        repositoryId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}/publish-sessions';
};

export type CreatePublishSessionErrors = {
    /**
     * Problem response
     */
    409: Problem;
};

export type CreatePublishSessionError = CreatePublishSessionErrors[keyof CreatePublishSessionErrors];

export type CreatePublishSessionResponses = {
    /**
     * Publish session
     */
    201: PublishSession;
};

export type CreatePublishSessionResponse = CreatePublishSessionResponses[keyof CreatePublishSessionResponses];

export type GetPublishSessionData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/publish-sessions/{sessionId}';
};

export type GetPublishSessionErrors = {
    /**
     * Problem response
     */
    404: Problem;
};

export type GetPublishSessionError = GetPublishSessionErrors[keyof GetPublishSessionErrors];

export type GetPublishSessionResponses = {
    /**
     * Publish session
     */
    200: PublishSession;
};

export type GetPublishSessionResponse = GetPublishSessionResponses[keyof GetPublishSessionResponses];

export type UploadPublishObjectData = {
    body: string;
    path: {
        sessionId: string;
        objectName: string;
    };
    query?: never;
    url: '/publish-sessions/{sessionId}/objects/{objectName}';
};

export type UploadPublishObjectErrors = {
    /**
     * Problem response
     */
    409: Problem;
    /**
     * Problem response
     */
    422: Problem;
};

export type UploadPublishObjectError = UploadPublishObjectErrors[keyof UploadPublishObjectErrors];

export type UploadPublishObjectResponses = {
    /**
     * Verified and staged
     */
    204: void;
};

export type UploadPublishObjectResponse = UploadPublishObjectResponses[keyof UploadPublishObjectResponses];

export type CommitPublishSessionData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/publish-sessions/{sessionId}:commit';
};

export type CommitPublishSessionErrors = {
    /**
     * Problem response
     */
    409: Problem;
    /**
     * Problem response
     */
    422: Problem;
};

export type CommitPublishSessionError = CommitPublishSessionErrors[keyof CommitPublishSessionErrors];

export type CommitPublishSessionResponses = {
    /**
     * Artifact
     */
    200: Artifact;
};

export type CommitPublishSessionResponse = CommitPublishSessionResponses[keyof CommitPublishSessionResponses];

export type ListArtifactsData = {
    body?: never;
    path: {
        repositoryId: string;
    };
    query?: {
        pageSize?: number;
        pageToken?: string;
    };
    url: '/repositories/{repositoryId}/artifacts';
};

export type ListArtifactsResponses = {
    /**
     * Artifact page
     */
    200: ArtifactPage;
};

export type ListArtifactsResponse = ListArtifactsResponses[keyof ListArtifactsResponses];

export type DeleteArtifactData = {
    body?: never;
    path: {
        repositoryId: string;
        artifactId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}/artifacts/{artifactId}';
};

export type DeleteArtifactResponses = {
    /**
     * Accepted deletion
     */
    202: Deletion;
};

export type DeleteArtifactResponse = DeleteArtifactResponses[keyof DeleteArtifactResponses];

export type GetArtifactData = {
    body?: never;
    path: {
        repositoryId: string;
        artifactId: string;
    };
    query?: never;
    url: '/repositories/{repositoryId}/artifacts/{artifactId}';
};

export type GetArtifactResponses = {
    /**
     * Artifact
     */
    200: Artifact;
};

export type GetArtifactResponse = GetArtifactResponses[keyof GetArtifactResponses];

export type ClientOptions = {
    baseUrl: 'https://gateway.example.com/api/v2' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | 'https://gateway.example.com' | (string & {});
};