#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
environment_file=${GATEWAY_ENV_FILE:-$repo_root/.env}
environment_template="$repo_root/.env.example"
state_dir=${GATEWAY_DEV_STATE_DIR:-$repo_root/.local-dev}
console_pid_file="$state_dir/console.pid"
console_log_file="$state_dir/console.log"
console_label="com.artifact-gateway.console.$(printf '%s' "$repo_root" | cksum | awk '{print $1}')"

read_local_dev_value() {
  local name=$1
  awk -F= -v name="$name" '$1 == name { print substr($0, index($0, "=") + 1); exit }' <<<"$local_dev_environment"
}

read_environment_value() {
  local name=$1
  awk -F= -v name="$name" '$1 == name { print substr($0, index($0, "=") + 1); exit }' "$environment_file"
}

is_environment_placeholder() {
  [[ -z "$1" || "$1" == replace-with-* ]]
}

bootstrap_local_environment() {
  command -v openssl >/dev/null 2>&1 || {
    printf 'openssl is required to generate local development credentials.\n' >&2
    return 1
  }

  local created=0
  if [[ ! -f "$environment_file" ]]; then
    [[ -f "$environment_template" ]] || {
      printf 'Missing environment template %s.\n' "$environment_template" >&2
      return 1
    }
    mkdir -p "$(dirname "$environment_file")"
    local initial_file
    initial_file=$(mktemp "${environment_file}.bootstrap.XXXXXX")
    if ! cp "$environment_template" "$initial_file" || ! chmod 600 "$initial_file" || ! mv "$initial_file" "$environment_file"; then
      rm -f "$initial_file"
      printf 'Unable to create %s from %s.\n' "$environment_file" "$environment_template" >&2
      return 1
    fi
    created=1
  fi

  local postgres_password admin_token resolver_token access_key secret_key rpc_secret changed=0
  postgres_password=$(read_environment_value GATEWAY_POSTGRES_PASSWORD)
  admin_token=$(read_environment_value GATEWAY_ADMIN_TOKEN)
  resolver_token=$(read_environment_value GATEWAY_RESOLVER_TOKEN)
  access_key=$(read_environment_value RUSTFS_ACCESS_KEY)
  secret_key=$(read_environment_value RUSTFS_SECRET_KEY)
  rpc_secret=$(read_environment_value RUSTFS_RPC_SECRET)

  if is_environment_placeholder "$postgres_password"; then postgres_password=$(openssl rand -hex 24); changed=1; fi
  if is_environment_placeholder "$admin_token"; then admin_token=$(openssl rand -hex 32); changed=1; fi
  if is_environment_placeholder "$resolver_token"; then resolver_token=$(openssl rand -hex 32); changed=1; fi
  if is_environment_placeholder "$access_key"; then access_key=$(openssl rand -hex 12); changed=1; fi
  if is_environment_placeholder "$secret_key"; then secret_key=$(openssl rand -hex 24); changed=1; fi
  if is_environment_placeholder "$rpc_secret"; then rpc_secret=$(openssl rand -hex 32); changed=1; fi

  if [[ ${#postgres_password} -lt 32 || ${#admin_token} -lt 32 || ${#resolver_token} -lt 32 ||
    ${#access_key} -lt 16 || ${#secret_key} -lt 32 || ${#rpc_secret} -lt 32 || "$secret_key" == "$rpc_secret" ]]; then
    printf 'Existing required credentials in %s do not satisfy the local security boundary.\n' "$environment_file" >&2
    return 1
  fi
  if [[ "$changed" == 0 ]]; then
    chmod 600 "$environment_file"
    printf 'Required local development credentials are already configured in %s.\n' "$environment_file"
    return
  fi

  local backup_dir backup_file temporary_file
  backup_dir="$state_dir/environment-backups"
  backup_file=
  if [[ "$created" == 0 ]]; then
    mkdir -p "$backup_dir"
    chmod 700 "$backup_dir"
    backup_file="$backup_dir/$(basename "$environment_file").before-bootstrap-$(date -u +%Y%m%dT%H%M%SZ)-$$"
    cp -p "$environment_file" "$backup_file"
  fi
  temporary_file=$(mktemp "${environment_file}.bootstrap.XXXXXX")
  if ! {
    awk '!/^(GATEWAY_POSTGRES_PASSWORD|GATEWAY_ADMIN_TOKEN|GATEWAY_RESOLVER_TOKEN|RUSTFS_ACCESS_KEY|RUSTFS_SECRET_KEY|RUSTFS_RPC_SECRET)=/' "$environment_file" >"$temporary_file" &&
      printf '\n# Required local credentials generated by scripts/local-dev.sh; never commit this file.\n' >>"$temporary_file" &&
      printf 'GATEWAY_POSTGRES_PASSWORD=%s\n' "$postgres_password" >>"$temporary_file" &&
      printf 'GATEWAY_ADMIN_TOKEN=%s\n' "$admin_token" >>"$temporary_file" &&
      printf 'GATEWAY_RESOLVER_TOKEN=%s\n' "$resolver_token" >>"$temporary_file" &&
      printf 'RUSTFS_ACCESS_KEY=%s\n' "$access_key" >>"$temporary_file" &&
      printf 'RUSTFS_SECRET_KEY=%s\n' "$secret_key" >>"$temporary_file" &&
      printf 'RUSTFS_RPC_SECRET=%s\n' "$rpc_secret" >>"$temporary_file" &&
      chmod 600 "$temporary_file" &&
      mv "$temporary_file" "$environment_file"
  }; then
    rm -f "$temporary_file"
    printf 'Unable to atomically update %s; the original file is unchanged.\n' "$environment_file" >&2
    return 1
  fi
  if [[ -n "$backup_file" ]]; then
    printf 'Configured required local credentials in %s; rollback copy: %s\n' "$environment_file" "$backup_file"
  else
    printf 'Created %s with generated local-only credentials.\n' "$environment_file"
  fi
}

bootstrap_rustfs_environment() {
  [[ -f "$environment_file" ]] || {
    printf 'Missing %s; copy .env.example before migrating local RustFS credentials.\n' "$environment_file" >&2
    return 1
  }
  command -v openssl >/dev/null 2>&1 || {
    printf 'openssl is required to generate independent local RustFS credentials.\n' >&2
    return 1
  }

  local access_key secret_key rpc_secret backup_dir backup_file temporary_file
  access_key=$(read_environment_value RUSTFS_ACCESS_KEY)
  secret_key=$(read_environment_value RUSTFS_SECRET_KEY)
  rpc_secret=$(read_environment_value RUSTFS_RPC_SECRET)
  if ! is_environment_placeholder "$access_key" && ! is_environment_placeholder "$secret_key" && ! is_environment_placeholder "$rpc_secret"; then
    if [[ ${#access_key} -lt 16 || ${#secret_key} -lt 32 || ${#rpc_secret} -lt 32 || "$secret_key" == "$rpc_secret" ]]; then
      printf 'Existing RustFS credentials in %s do not satisfy the local security boundary.\n' "$environment_file" >&2
      return 1
    fi
    printf 'RustFS credentials are already configured in %s.\n' "$environment_file"
    return
  fi

  if is_environment_placeholder "$access_key"; then access_key=$(openssl rand -hex 12); fi
  if is_environment_placeholder "$secret_key"; then secret_key=$(openssl rand -hex 24); fi
  if is_environment_placeholder "$rpc_secret"; then rpc_secret=$(openssl rand -hex 32); fi
  if [[ ${#access_key} -lt 16 || ${#secret_key} -lt 32 || ${#rpc_secret} -lt 32 || "$secret_key" == "$rpc_secret" ]]; then
    printf 'Unable to produce valid independent RustFS credentials.\n' >&2
    return 1
  fi

  backup_dir="$state_dir/rustfs-env-backups"
  mkdir -p "$backup_dir"
  chmod 700 "$backup_dir"
  backup_file="$backup_dir/$(basename "$environment_file").before-rustfs-$(date -u +%Y%m%dT%H%M%SZ)-$$"
  temporary_file=$(mktemp "${environment_file}.rustfs.XXXXXX")
  if ! {
    cp -p "$environment_file" "$backup_file" &&
      awk '!/^RUSTFS_(ACCESS_KEY|SECRET_KEY|RPC_SECRET)=/' "$environment_file" >"$temporary_file" &&
      printf '\n# Local RustFS credentials generated by scripts/local-dev.sh; never commit this file.\n' >>"$temporary_file" &&
      printf 'RUSTFS_ACCESS_KEY=%s\n' "$access_key" >>"$temporary_file" &&
      printf 'RUSTFS_SECRET_KEY=%s\n' "$secret_key" >>"$temporary_file" &&
      printf 'RUSTFS_RPC_SECRET=%s\n' "$rpc_secret" >>"$temporary_file" &&
      chmod "$(stat -f '%Lp' "$environment_file" 2>/dev/null || stat -c '%a' "$environment_file")" "$temporary_file" &&
      mv "$temporary_file" "$environment_file"
  }; then
    rm -f "$temporary_file"
    printf 'Unable to atomically update %s; the original file is unchanged.\n' "$environment_file" >&2
    return 1
  fi
  printf 'Added independent RustFS credentials to %s; rollback copy: %s\n' "$environment_file" "$backup_file"
}

local_dev_environment=
if [[ -f "$environment_file" ]] && command -v docker >/dev/null 2>&1; then
  local_dev_environment=$(
    docker compose --env-file "$environment_file" -f "$repo_root/compose.yml" config 2>/dev/null |
      awk '
        $0 == "x-local-dev:" { local_dev = 1; next }
        local_dev && /^[^[:space:]]/ { exit }
        local_dev && ($1 == "gateway-port:" || $1 == "console-port:") {
          name = $1
          sub(/-port:$/, "", name)
          value = $2
          gsub(/^"|"$/, "", value)
          print name "=" value
        }
      ' || true
  )
fi

gateway_port=${GATEWAY_HTTP_PORT:-$(read_local_dev_value gateway)}
gateway_port=${gateway_port:-8080}
console_port=${GATEWAY_CONSOLE_PORT:-$(read_local_dev_value console)}
console_port=${console_port:-4173}
gateway_url="http://127.0.0.1:${gateway_port}"
console_url="http://127.0.0.1:${console_port}"

http_status() {
  curl --noproxy '*' --silent --show-error --output /dev/null --write-out '%{http_code}' --max-time 3 "$1" 2>/dev/null || true
}

check_endpoint() {
  local label=$1
  local url=$2
  local expected=$3
  local code
  code=$(http_status "$url")
  printf '%-8s %s  HTTP %s\n' "$label" "$url" "${code:-000}"
  [[ "$code" == "$expected" ]]
}

refuse_legacy_minio_in_place() {
	local project=${COMPOSE_PROJECT_NAME:-artifact-gateway}
	local old_volume="${project}_gateway-minio"
	local legacy_container
  legacy_container=$(docker ps -aq \
    --filter "label=com.docker.compose.project=$project" \
    --filter 'label=com.docker.compose.service=minio')
  if [[ -z "$legacy_container" ]] && ! docker volume inspect "$old_volume" >/dev/null 2>&1; then
    return
  fi
	printf '%s\n' 'Unsupported legacy MinIO resources were detected; remove or rename them explicitly before starting the RustFS-only stack.' >&2
	printf '%s\n' 'The helper never deletes legacy volumes and no longer provides an in-place compatibility or migration bypass.' >&2
  return 1
}

console_is_managed() {
  if [[ $(uname -s) == Darwin ]]; then
    launchctl print "gui/$(id -u)/$console_label" >/dev/null 2>&1
    return
  fi
  [[ -f "$console_pid_file" ]] || return 1
  local pid recorded_start_time current_start_time
  read -r pid recorded_start_time <"$console_pid_file" || return 1
  [[ "$pid" =~ ^[0-9]+$ && "$recorded_start_time" =~ ^[0-9]+$ ]] || return 1
  kill -0 "$pid" 2>/dev/null || return 1
  current_start_time=$(process_start_time "$pid") || return 1
  [[ "$current_start_time" == "$recorded_start_time" ]]
}

process_start_time() {
  local pid=$1
  local process_stat fields_after_name
  [[ -r "/proc/$pid/stat" ]] || return 1
  process_stat=$(<"/proc/$pid/stat")
  fields_after_name=${process_stat##*) }
  awk '{ print $20 }' <<<"$fields_after_name"
}

start_console() {
  local node_binary
  node_binary=$(command -v node || true)
  [[ -n "$node_binary" ]] || {
    printf 'Node.js is required to start the Console.\n' >&2
    return 1
  }
  if [[ ! -x "$repo_root/console/node_modules/.bin/vite" ]]; then
    npm --prefix "$repo_root/console" ci
  fi

  mkdir -p "$state_dir"
  if [[ $(uname -s) == Darwin ]]; then
    launchctl submit -l "$console_label" -o "$console_log_file" -e "$console_log_file" -- \
      /usr/bin/env VITE_GATEWAY_PROXY_TARGET="$gateway_url" \
      "$node_binary" "$repo_root/console/node_modules/.bin/vite" "$repo_root/console" --host 127.0.0.1 --port "$console_port" --strictPort
    return
  fi

  VITE_GATEWAY_PROXY_TARGET="$gateway_url" nohup \
    "$node_binary" "$repo_root/console/node_modules/.bin/vite" "$repo_root/console" --host 127.0.0.1 --port "$console_port" --strictPort >"$console_log_file" 2>&1 </dev/null &
  local pid=$!
  local start_time
  start_time=$(process_start_time "$pid") || {
    printf 'Cannot verify the Console process identity through /proc.\n' >&2
    return 1
  }
  printf '%s %s\n' "$pid" "$start_time" >"$console_pid_file"
}

stop_console() {
  if [[ $(uname -s) == Darwin ]]; then
    if console_is_managed; then
      launchctl remove "$console_label"
      for _ in {1..50}; do
        if ! console_is_managed && [[ $(http_status "$console_url/") != 200 ]]; then
          return 0
        fi
        sleep 0.1
      done
      printf 'Console supervisor did not stop within 5 seconds.\n' >&2
      return 1
    fi
    return 0
  fi
  if console_is_managed; then
    local pid _start_time
    read -r pid _start_time <"$console_pid_file"
    kill "$pid"
    for _ in {1..50}; do
      kill -0 "$pid" 2>/dev/null || break
      sleep 0.1
    done
    kill -0 "$pid" 2>/dev/null && {
      printf 'Console process did not stop within 5 seconds.\n' >&2
      return 1
    }
    rm -f "$console_pid_file"
  elif [[ -f "$console_pid_file" ]]; then
    rm -f "$console_pid_file"
  fi
}

start() {
  [[ -f "$environment_file" ]] || {
    printf 'Missing %s; copy .env.example and configure local credentials first.\n' "$environment_file" >&2
    return 1
  }
  refuse_legacy_minio_in_place

  docker compose --env-file "$environment_file" -f "$repo_root/compose.yml" up -d --build --wait --remove-orphans
  local console_code
  console_code=$(http_status "$console_url/")
  if console_is_managed; then
    stop_console
    console_code=000
  elif [[ "$console_code" == 200 ]]; then
    printf 'Console is already reachable at %s but is not managed by this checkout; it was left unchanged.\n' "$console_url"
    status
    return 0
  fi

  start_console
  for _ in {1..100}; do
    console_code=$(http_status "$console_url/")
    [[ "$console_code" == 200 ]] && break
    if ! console_is_managed; then
      printf 'Console exited before becoming ready. Recent log output:\n' >&2
      tail -n 40 "$console_log_file" >&2 || true
      return 1
    fi
    sleep 0.1
  done
  if [[ "$console_code" != 200 ]]; then
    stop_console || true
    printf 'Console did not become ready at %s within 10 seconds.\n' "$console_url" >&2
    return 1
  fi
  status
}

status() {
  local failed=0

  check_endpoint Console "$console_url/" 200 || failed=1
  check_endpoint 'Console API' "$console_url/api/v2/public/repositories" 200 || failed=1
  check_endpoint 'Gateway livez' "$gateway_url/livez" 204 || failed=1
  check_endpoint 'Gateway readyz' "$gateway_url/readyz" 204 || failed=1

  return "$failed"
}

stop() {
  [[ -f "$environment_file" ]] || {
    printf 'Missing %s; nothing was stopped.\n' "$environment_file" >&2
    return 1
  }
  stop_console
  printf 'Stopped Console; Gateway and data volumes remain running.\n'
}

case ${1:-} in
  bootstrap-env) bootstrap_local_environment ;;
  bootstrap-rustfs-env) bootstrap_rustfs_environment ;;
  guard)
    [[ -f "$environment_file" ]] || {
      printf 'Missing %s; cannot validate the RustFS cutover boundary.\n' "$environment_file" >&2
      exit 1
    }
    refuse_legacy_minio_in_place
    ;;
  start) start ;;
  status) status ;;
  stop) stop ;;
  *)
		printf 'usage: %s {bootstrap-env|bootstrap-rustfs-env|guard|start|status|stop}\n' "${0##*/}" >&2
    exit 2
    ;;
esac
